version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
       - cd lambda/f5_sca_libs
       - make install 
       - pipenv run make test
       - make wheel
artifacts:
  files:
    - lambda/f5_sca_libs/dist/f5_sca_libs-1.0.0-py3-none-any.whl
  discard-paths: yes
