version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
       - cd lambda/f5_sca_libs
       - make install 
       - pipenv run make test
       - make wheel
